image: python:3.8

pages:
  script:
  - pip install --no-cache-dir -r requirements.txt
  - FLASK_APP=app.py flask freeze
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
